### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by dedimark** [nosoop/SM-TFUtils#9]
Soucemod - 1.11 - build 6919 

//// tf2utils.sp
//
// tf2utils.sp(500) : warning 209: function has explicit 'int' tag but does not return a value
// tf2utils.sp(559) : warning 209: function has explicit 'int' tag but does not return a value
// tf2utils.sp(580) : warning 209: function has explicit 'int' tag but does not return a value
// tf2utils.sp(610) : warning 209: function has explicit 'int' tag but does not return a value
// tf2utils.sp(776) : warning 242: function "Native_SetPlayerConditionDuration" should return an explicit value
// tf2utils.sp(808) : warning 242: function "Native_SetPlayerConditionProvider" should return an explicit value
// tf2utils.sp(836) : warning 242: function "Native_SetPlayerBurnDuration" should return an explicit value
// tf2utils.sp(836) : warning 242: function "Native_SetPlayerBurnDuration" should return an explicit value
// tf2utils.sp(849) : warning 242: function "Native_IgnitePlayer" should return an explicit value
// tf2utils.sp(971) : warning 242: function "Native_SetPlayerRespawnTimeOverride" should return an explicit value
// tf2utils.sp(971) : warning 242: function "Native_SetPlayerRespawnTimeOverride" should return an explicit value
// Code size:         31760 bytes
// Data size:         10000 bytes
// Stack/heap size:      16732 bytes
// Total requirements:   58492 bytes
//
// 11 Warnings.
//
// Compilation Time: 0.48 sec

Can you fix please?

**Comment by nosoop** [comment]
Those are warnings, not errors.  The plugin was still successfully compiled.

I'll consider dealing with SourceMod compiler churn in a future commit.
